from __future__ import annotations

import json

import psycopg
from pgvector import Vector
from pgvector.psycopg import register_vector
from psycopg.rows import dict_row

from app.config import INTERVIEW_QUESTIONS_FILE, settings
from app.llm import GeminiClient


EMBEDDING_DIM = 768


class RagStore:
    def __init__(self) -> None:
        if not settings.database_url:
            raise RuntimeError("DATABASE_URL이 없음")

        self.conn = psycopg.connect(
            settings.database_url,
            autocommit=True,
            row_factory=dict_row,
        )
        self._setup()
        register_vector(self.conn)

    def close(self) -> None:
        self.conn.close()

    def _setup(self) -> None:
        with self.conn.cursor() as cur:
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS student_record_chunks (
                    content TEXT NOT NULL,
                    embedding vector({EMBEDDING_DIM}) NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
                )
                """
            )
            cur.execute("ALTER TABLE student_record_chunks DROP COLUMN IF EXISTS id CASCADE")
            cur.execute("ALTER TABLE student_record_chunks DROP COLUMN IF EXISTS category")
            cur.execute(
                """
                SELECT data_type
                FROM information_schema.columns
                WHERE table_name = 'interview_questions' AND column_name = 'id'
                """
            )
            id_column = cur.fetchone()
            if id_column and id_column["data_type"] not in {"bigint", "integer"}:
                cur.execute("DROP TABLE interview_questions")
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS interview_questions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    university TEXT NOT NULL,
                    admission_type TEXT NOT NULL,
                    department TEXT NOT NULL,
                    question TEXT NOT NULL,
                    search_context TEXT NOT NULL,
                    embedding vector({EMBEDDING_DIM}) NOT NULL
                )
                """
            )
            cur.execute("ALTER TABLE interview_questions DROP COLUMN IF EXISTS category")

    async def seed_interview_questions(self, llm: GeminiClient) -> int:
        with self.conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) AS count FROM interview_questions")
            count = cur.fetchone()["count"]
        if count > 0:
            return count

        rows = json.loads(INTERVIEW_QUESTIONS_FILE.read_text(encoding="utf-8"))
        documents = [(row.get("search_context")) for row in rows]
        embeddings = await _embed_in_batches(llm, documents)

        values = []
        for row, document, embedding in zip(rows, documents, embeddings):
            values.append(
                (
                    row.get("university") or "미상",
                    row.get("admission_type") or "미상",
                    row.get("department") or "미상",
                    row.get("question") or "",
                    document,
                    Vector(embedding),
                )
            )

        with self.conn.cursor() as cur:
            cur.executemany(
                """
                INSERT INTO interview_questions (
                    university, admission_type, department,
                    question, search_context, embedding
                )
                VALUES (%s, %s, %s, %s, %s, %s)
                """,
                values,
            )
        return len(values)

    def has_record(self) -> bool:
        with self.conn.cursor() as cur:
            cur.execute(
                """
                SELECT COUNT(*) > 0 AS has_record
                FROM student_record_chunks
                """
            )
            return bool(cur.fetchone()["has_record"])

    async def add_record_chunks(
        self,
        *,
        chunks: list[dict[str, str]],
        llm: GeminiClient,
    ) -> int:
        if not chunks:
            return 0

        documents = [chunk["content"] for chunk in chunks]
        embeddings = await _embed_in_batches(llm, documents)
        values = [
            (
                document,
                Vector(embedding),
            )
            for document, embedding in zip(documents, embeddings)
        ]

        with self.conn.cursor() as cur:
            cur.execute("DELETE FROM student_record_chunks")
            cur.executemany(
                """
                INSERT INTO student_record_chunks (
                    content, embedding
                )
                VALUES (%s, %s)
                """,
                values,
            )
        return len(chunks)

    async def search_record_chunks(
        self,
        *,
        query: str,
        llm: GeminiClient,
        limit: int = 5,
    ) -> list[str]:
        query_embedding = Vector((await llm.embed_texts([query]))[0])
        with self.conn.cursor() as cur:
            cur.execute(
                """
                SELECT content
                FROM student_record_chunks
                ORDER BY embedding <=> %s
                LIMIT %s
                """,
                (query_embedding, limit),
            )
            return [row["content"] for row in cur.fetchall()]

    async def search_interview_questions(
        self,
        *,
        query: str,
        llm: GeminiClient,
        limit: int = 5,
    ) -> list[str]:
        query_embedding = Vector((await llm.embed_texts([query]))[0])
        with self.conn.cursor() as cur:
            cur.execute(
                """
                SELECT question
                FROM interview_questions
                ORDER BY embedding <=> %s
                LIMIT %s
                """,
                (query_embedding, limit),
            )
            return [row["question"] for row in cur.fetchall() if row["question"]]


async def _embed_in_batches(llm: GeminiClient, texts: list[str], batch_size: int = 32) -> list[list[float]]:
    embeddings: list[list[float]] = []
    for start in range(0, len(texts), batch_size):
        embeddings.extend(await llm.embed_texts(texts[start : start + batch_size]))
    return embeddings
